import { escape } from "html-escaper";

export type ReportTemplateKey = "performance" | "risk" | "compliance" | "custom";

export type ReportInput = {
  title?: string;
  period?: string;
  generatedBy?: string;
  generatedAt?: string; // ISO
  summary?: string;
  metrics?: Array<{ label: string; value: string; color?: string }>;
  sections?: Array<{ heading: string; body: string }>;
  charts?: Array<{ title: string; type: string; data: any }>;
};

function baseHTML(title: string, body: string) {
  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escape(title)}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    :root {
      --bg: #ffffff;
      --fg: #0f172a;
      --muted: #475569;
      --accent: #6d28d9;
      --good: #16a34a;
      --warn: #f59e0b;
      --bad: #dc2626;
      --card: #f8fafc;
      --border: #e2e8f0;
    }
    @page { size: A4; margin: 24mm 18mm; }
    body { 
      background: var(--bg); 
      color: var(--fg); 
      font-family: system-ui, -apple-system, "Segoe UI", Roboto, Ubuntu, Cantarell, "Noto Sans", Helvetica, Arial, sans-serif;
      line-height: 1.5;
      margin: 0;
      padding: 0;
    }
    .page { page-break-after: always; }
    .container { width: 100%; max-width: 210mm; margin: 0 auto; }
    h1, h2, h3 { margin: 0 0 12px; }
    .title { font-size: 28px; font-weight: 800; color: var(--fg); margin-bottom: 8px; }
    .subtitle { color: var(--muted); margin-bottom: 16px; font-size: 14px; }
    .section { margin-top: 24px; padding: 16px; background: var(--card); border: 1px solid var(--border); border-radius: 8px; }
    .metrics-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin: 24px 0; }
    .metric { padding: 16px; border: 1px dashed var(--border); border-radius: 8px; background: white; }
    .metric .label { font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.5px; }
    .metric .value { font-size: 24px; font-weight: 700; margin-top: 4px; }
    .metric .value.good { color: var(--good); }
    .metric .value.warn { color: var(--warn); }
    .metric .value.bad { color: var(--bad); }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 999px; font-size: 12px; background: #ede9fe; color: var(--accent); font-weight: 600; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid var(--border); font-size: 12px; color: var(--muted); display: flex; justify-content: space-between; }
    .section h3 { color: var(--accent); margin-bottom: 12px; }
    .muted { color: var(--muted); }
    .mono { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; }
    .logo { font-weight: 800; color: var(--accent); font-size: 18px; }
    .summary-box { background: #f0f9ff; border: 1px solid #0284c7; padding: 16px; border-radius: 8px; margin: 16px 0; }
  </style>
</head>
<body>
  <div class="container">
    ${body}
  </div>
</body>
</html>`;
}

function headerBlock(kind: string, input: ReportInput) {
  const now = input.generatedAt ?? new Date().toISOString();
  const formatDate = (iso: string) => new Date(iso).toLocaleDateString('en-US', { 
    year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' 
  });
  
  const period = input.period ? `<span class="badge">Period: ${escape(input.period)}</span>` : "";
  const by = input.generatedBy ? `<div class="muted">Generated by: ${escape(input.generatedBy)}</div>` : "";
  const summary = input.summary ? `<div class="summary-box">${escape(input.summary)}</div>` : "";
  
  return `
    <div style="margin-bottom: 32px;">
      <div style="display: flex; justify-content: space-between; align-items: start; margin-bottom: 16px;">
        <div>
          <h1 class="title">${escape(input.title || `${kind} Report`)}</h1>
          <div class="subtitle">
            <strong>GeFi ${escape(kind)} Report</strong> • Generated on ${formatDate(now)}
          </div>
          <div style="margin-top: 8px;">${period}</div>
          ${by}
        </div>
        <div class="logo">GeFi</div>
      </div>
      ${summary}
    </div>
  `;
}

function metricsGrid(metrics?: Array<{ label: string; value: string; color?: string }>) {
  if (!metrics?.length) return "";
  
  const items = metrics
    .map((m) => {
      const colorClass = m.color === 'good' ? 'good' : m.color === 'warn' ? 'warn' : m.color === 'bad' ? 'bad' : '';
      return `
        <div class="metric">
          <div class="label">${escape(m.label)}</div>
          <div class="value ${colorClass}">${escape(m.value)}</div>
        </div>`;
    })
    .join("");
    
  return `<div class="metrics-grid">${items}</div>`;
}

function sectionsBlock(sections?: Array<{ heading: string; body: string }>) {
  if (!sections?.length) return "";
  return sections
    .map((s) => `
      <div class="section">
        <h3>${escape(s.heading)}</h3>
        <div>${s.body}</div>
      </div>`)
    .join("");
}

export function buildReportHTML(template: ReportTemplateKey, input: ReportInput): string {
  const kindMap = {
    performance: "Performance",
    risk: "Risk Assessment", 
    compliance: "Compliance",
    custom: "Custom"
  };
  
  const kind = kindMap[template] || "Report";

  const body = `
    ${headerBlock(kind, input)}
    ${metricsGrid(input.metrics)}
    ${sectionsBlock(input.sections)}
    <div class="footer">
      <span>© ${new Date().getFullYear()} GeFi - AI-Powered Financial Platform</span>
      <span class="mono">Template: ${escape(template)} | Generated: ${escape(new Date().toISOString())}</span>
    </div>
  `;

  return baseHTML(input.title || `${kind} Report`, body);
}

export function getTemplateFields(template: ReportTemplateKey): Array<{ name: string; label: string; type: string; required?: boolean }> {
  const baseFields = [
    { name: "title", label: "Report Title", type: "text", required: true },
    { name: "period", label: "Reporting Period", type: "text" },
    { name: "summary", label: "Executive Summary", type: "textarea" }
  ];

  switch (template) {
    case "performance":
      return [
        ...baseFields,
        { name: "portfolio_value", label: "Portfolio Value", type: "currency" },
        { name: "total_return", label: "Total Return", type: "percentage" },
        { name: "benchmark_comparison", label: "vs Benchmark", type: "percentage" }
      ];
    case "risk":
      return [
        ...baseFields,
        { name: "var_95", label: "VaR (95%)", type: "currency" },
        { name: "risk_score", label: "Risk Score", type: "number" },
        { name: "stress_test_result", label: "Stress Test Result", type: "text" }
      ];
    case "compliance":
      return [
        ...baseFields,
        { name: "compliance_rate", label: "Compliance Rate", type: "percentage" },
        { name: "violations_count", label: "Violations", type: "number" },
        { name: "regulatory_framework", label: "Framework", type: "text" }
      ];
    default:
      return baseFields;
  }
}